# Generated by Django 3.2 on 1979-12-31 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ekereapp', '0007_alter_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birth_day',
            field=models.DateField(null=True),
        ),
    ]
