# Generated by Django 3.2 on 1980-01-01 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ekereapp', '0010_alter_userprofile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(blank=True, default='user.png', null=True, upload_to='profile_pic/'),
        ),
    ]
