# Generated by Django 3.2 on 1980-01-01 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ekereapp', '0011_alter_userprofile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(blank=True, default='profile/user.png', null=True, upload_to='profile_pic/'),
        ),
    ]
